CREATE TABLE users (
	id UUID PRIMARY KEY,
	email TEXT UNIQUE NOT NULL,
	website TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
	id UUID PRIMARY KEY,
	sender_id UUID REFERENCES users(id),
	receiver_id UUID REFERENCES users(id),
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
